config/routes.rb
Farmacia::Application.routes.draw do
  resources :medicines

  resources :produtos

  resources :categoria

  resources :remedios
  root to: "remedios#index"

end

app/models/remedio.rb
class Remedio < ActiveRecord::Base
  attr_accessible :composicao, :nome, :preco, :entrega, :receita
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/remedios_controller.rb
class RemediosController < ApplicationController
  # GET /remedios
  # GET /remedios.json
  def index
    @remedios = Remedio.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @remedios }
    end
  end

  # GET /remedios/1
  # GET /remedios/1.json
  def show
    @remedio = Remedio.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @remedio }
    end
  end

  # GET /remedios/new
  # GET /remedios/new.json
  def new
    @remedio = Remedio.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @remedio }
    end
  end

  # GET /remedios/1/edit
  def edit
    @remedio = Remedio.find(params[:id])
  end

  # POST /remedios
  # POST /remedios.json
  def create
    @remedio = Remedio.new(params[:remedio])

    respond_to do |format|
      if @remedio.save
        format.html { redirect_to @remedio, notice: 'Remedio was successfully created.' }
        format.json { render json: @remedio, status: :created, location: @remedio }
      else
        format.html { render action: "new" }
        format.json { render json: @remedio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /remedios/1
  # PUT /remedios/1.json
  def update
    @remedio = Remedio.find(params[:id])

    respond_to do |format|
      if @remedio.update_attributes(params[:remedio])
        format.html { redirect_to @remedio, notice: 'Remedio was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @remedio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /remedios/1
  # DELETE /remedios/1.json
  def destroy
    @remedio = Remedio.find(params[:id])
    @remedio.destroy

    respond_to do |format|
      format.html { redirect_to remedios_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categoria_helper.rb
module CategoriaHelper
end

app/helpers/medicines_helper.rb
module MedicinesHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/remedios_helper.rb
module RemediosHelper
end

app/views/layouts/application.html.haml
%DOCTYPE
%html
%head
  %title Farmacia
  = stylesheet_link_tag    "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags
%body

= yield

app/views/remedios/_form.html.haml
= semantic_form_for @remedio do |f|
  = f.inputs do
    = f.input :nome
    = f.input :preco
    = f.input :composicao
    = f.input :entrega, start_year: 2013
    = f.input :receita, :as => :radio, :collection => [["Não", false], ["Sim", true]]
  = f.actions do
    = f.action :submit, :as => :input

app/views/remedios/edit.html.haml
%h1.Editing Remédio

= render 'form'

= link_to 'Show', @remedio
= link_to 'Back', remedios_path

app/views/remedios/index.html.haml
%h1.Listing Remédios

%table{style: "width: 600px"}
  %tr
    %th Nome
    %th Preco
    %th Composicao
    %th Receita
    %th Entrega

  - @remedios.each do |remedio|
    %tr
    %td= remedio.nome
    %td= remedio.preco
    %td= remedio.composicao
    %td= remedio.receita
    %td= remedio.entrega
    %td= link_to 'Show', remedio
    %td= link_to 'Edit', edit_remedio_path(remedio)
    %td= link_to 'Destroy', remedio, method: :delete, data: { confirm: 'Are you sure?' }
    %br/
%br/

= link_to 'Novo Remedio', new_remedio_path

app/views/remedios/new.html.haml
%h1.New Remédio

= render 'form'

= link_to 'Back', remedios_path

app/views/remedios/show.html.haml
#notice= notice

%p
  %b Nome:
  = @remedio.nome

%p
  %b Preco:
  = @remedio.preco

%p
  %b Composicao:
  = @remedio.composicao

%p
  %b Receita:
  = @remedio.receita

%p
  %b Entrega:
  = @remedio.entrega


= link_to 'Edit', edit_remedio_path(@remedio)
= link_to 'Back', remedios_path